name: Daily Build

on:
  schedule:
    - cron: '0 2 * * *'   # daily at 02:00 UTC
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    uses: ./.github/workflows/release_full.yml
    with:
      release_prefix: nightly
      use_fixed_tag: true
    secrets: inherit
